spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Reservaciones
    username: postgres
    password: cdm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true